# Personal academic homepage configuration
url: "https://renee-st.github.io"
baseurl: ""

title: "Yujuan Yang"

markdown: kramdown
plugins:
  - jekyll-email-protect

timezone: Asia/Shanghai

collections:
  - publications
  - news
  - showcase
  - posts
